// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44315' | (string & {});
};

export type EasyEntityFlagModel = {
    propertyAlias?: string | null;
    icon?: string | null;
    iconColorAlias?: string | null;
    label?: string | null;
    weight: number;
    forEntityTypes?: Array<string> | null;
    condition: FlagCondition;
    name?: string | null;
    alias?: string | null;
    flagName?: string | null;
};

export type FlagCondition = 'HasValue' | 'HasNoValue' | 'IsTrue' | 'IsFalse';

export type GetGetEntityFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/get-entity-flags';
};

export type GetGetEntityFlagsResponses = {
    /**
     * OK
     */
    200: Array<EasyEntityFlagModel>;
};

export type GetGetEntityFlagsResponse = GetGetEntityFlagsResponses[keyof GetGetEntityFlagsResponses];
